name: TeamBuildUHCJericMD
main: JMD\TeamBuildUHC\TeamBuildUHC
author: JericMinesDiamond
version: 1.0 Beta 1
api: [1.0.0, 2.0.0]

commands:
    tbuhc :
        usage: /tbuhc <leave-make>
        description: TeamBuildUHC-Commands
    lang:
        usage: /lang <en>
        description: TeamBuildUHC-English-Lang
    ranktbuhc :
        usage: /ranktbuhc 
        description: TeamBuildUHC-Commands
    tbuhc start:
        usage: /tbuhc start
        description: TeamBuildUHC-Force start